config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :weathers, only: [:index, :create, :new, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :weathers, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(email: data['email'],
        password: Devise.friendly_token[0,20]
      )
    end

    user
  end
end

app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :user

  validates :city, presence: true

  def self.to_celcius(temp)
   return 0 if temp == nil

   temp = (temp - 273.15)

   number = temp.to_s.split('.')
   result = number.last.to_i

   if result >= 50
     temp.ceil
   else
     temp.floor
   end
  end

  def self.date_format(date)
    date.strftime("%F")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :null_session, prepend: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
before_action :set_weather, only: %i[ edit update destroy ]

  def index
    @weathers = Weather.all
  end

  def new
    @weather = Weather.new
  end

  def edit
  end

  def create
    @weather = Weather.new(weather_params)
    @weather.user_id = current_user.id

    if @weather.save
      GetWeather.call(weather: @weather)

      redirect_to weathers_url, notice: "Zakończono sukcesem."
    end
  end

  def update
    if @weather.user_id == current_user.id && @weather.update(weather_params)
      UpdateWeather.call(weather: @weather)

      redirect_to weathers_url, notice: "Zakończono sukcesem."
    else
      redirect_to weathers_url, notice: "Zapis się nie powiódł."
    end
  end

  def destroy
    if @weather.user_id == current_user.id
      @weather.destroy
      redirect_to weathers_url, notice: "Zakończono sukcesem."
    else
      redirect_to weathers_url, notice: "Nie jesteś właścicielem tych wpisów!"
    end
  end

  private

  def set_weather
    @weather = Weather.find(params[:id])
  end

  def weather_params
    params.require(:weather).permit(:city, :note, :temp)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <div class="jumbotron">
    <h1 class="display-4">Witaj, <%= current_user.email %>!</h1>
    <p class="lead">Wprowadź nazwę miasta i dowiedz się jaka jest tam aktualnie pogoda!</p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OpenWeather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffffff;">
      <%= image_tag("logo1.png", width: 100, class: "image") %>
      <% if current_user %>
        <%= link_to("Sprawdź pogodę!", new_weather_path, class: "navbar-brand") %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to("Strona główna", root_path, class: "nav-link") %>
            </li>
            <li class="nav-item active">
              <%= link_to("Wykaz miast z pogodą", weathers_path, class: "nav-link") %>
            </li>
            <li class="nav-item active">
              <%= link_to(destroy_user_session_path, method: :delete, class: "nav-link") do %>
                Wyloguj się
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to(user_google_oauth2_omniauth_authorize_path, method: :post, class: "nav-link") do %>
                Zaloguj się z Google
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </nav>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/weathers/_form.html.erb
<%= form_with(model: weather) do |form| %>
  <% if weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
        <% weather.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.text_field :city, class: "form-control col-sm-3", placeholder: "Jaka miejscowość?" %>
  </div>
  <div class="form-group">
    <%= form.text_area :note, class: "form-control col-sm-3", placeholder: "Notatka", rows: "3" %>
  </div>
  <div class="btn-sumbit">
    <%= form.submit :Zapisz, class: "btn btn-outline-info col-sm-3" %>
  </div>
<% end %>

app/views/weathers/edit.html.erb
<div class="edit-weather">
  <h1>Edytuj</h1>
</div>

<%= render 'form', weather: @weather %>

<div class="btn-dark-new">
  <%= link_to('Powrót do strony głównej', weathers_path, class: "btn btn-outline-dark col-sm-3") %>
</div>

app/views/weathers/index.html.erb
<br>

<div class="btn-new">
  <%= link_to('Dodaj nowe miasto', new_weather_path, class: 'btn btn-outline-info') %>
</div>

<% @weathers.each do |weather| %>
  <div class="row">
    <div class="col-sm-5">
      <div class="card w-75">
        <div class="card-body">
          <p class="card-text-date"><%= Weather.date_format(weather.updated_at) %></p>
          <p class="card-text-data"><%= image_tag("logo1.png", width: 60) %>  <%= weather.city %>  <%= Weather.to_celcius(weather.temp) %><span>&#176;</span></p>
          <p class="card-text"><%= weather.note %></p>
          <% if current_user %>
            <%= link_to("Edytuj", edit_weather_path(weather), class: "btn btn-outline-secondary") %>
            <%= link_to(weather, method: :delete, class: "btn btn-outline-success") do %>
              Usuń
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/weathers/new.html.erb
<%= render 'form', weather: @weather %>

<div class="btn-dark-new">
  <%= link_to('Powrót do strony głównej', weathers_path, class: "btn btn-outline-dark col-sm-3") %>
</div>